"""Create ExpenseCategory, Expense and User models.

Revision ID: 1a3c78f4fbbb
Revises: 
Create Date: 2026-02-19 18:40:14.369942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3c78f4fbbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_category',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название категории'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание категории'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='Цвет категории (HEX)'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Иконка категории'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('expense',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма расхода'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание расхода'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='ID категории'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Дата совершения расхода'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('is_paid', sa.Boolean(), nullable=False, comment='Оплачен ли расход'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('expense_category')
    # ### end Alembic commands ###
