"""Remove description field in BaseCategory model.

Revision ID: 4fcfaf6680e4
Revises: ded7b2cfa6e9
Create Date: 2026-02-22 20:00:20.193364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcfaf6680e4'
down_revision: Union[str, Sequence[str], None] = 'ded7b2cfa6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_category', 'description')
    op.drop_column('income_category', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income_category', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('expense_category', sa.Column('description', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
