"""Remove color and icon field in ExpenseCategory model. Create IncomeCategory, Income models.

Revision ID: 9bcc07a9cfc0
Revises: 866d3c06d479
Create Date: 2026-02-22 15:30:14.872561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcc07a9cfc0'
down_revision: Union[str, Sequence[str], None] = '866d3c06d479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_category',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название категории'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание категории'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('income',
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='Сумма дохода'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание дохода'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='ID категории'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False, comment='Дата создания записи'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['income_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('expense_category', 'color')
    op.drop_column('expense_category', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_category', sa.Column('icon', sa.VARCHAR(length=50), nullable=True))
    op.add_column('expense_category', sa.Column('color', sa.VARCHAR(length=7), nullable=True))
    op.drop_table('income')
    op.drop_table('income_category')
    # ### end Alembic commands ###
