"""Add created_at field in Income model.

Revision ID: ded7b2cfa6e9
Revises: 9bcc07a9cfc0
Create Date: 2026-02-22 17:02:26.647519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded7b2cfa6e9'
down_revision: Union[str, Sequence[str], None] = '9bcc07a9cfc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата создания записи'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'created_at')
    # ### end Alembic commands ###
